[2025-05-06T06:09:57.987+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-06T06:09:58.045+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_mysql_connection.query_mysql manual__2025-05-06T06:09:56.652376+00:00 [queued]>
[2025-05-06T06:09:58.061+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_mysql_connection.query_mysql manual__2025-05-06T06:09:56.652376+00:00 [queued]>
[2025-05-06T06:09:58.063+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-06T06:09:58.086+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): query_mysql> on 2025-05-06 06:09:56.652376+00:00
[2025-05-06T06:09:58.099+0000] {standard_task_runner.py:63} INFO - Started process 483 to run task
[2025-05-06T06:09:58.105+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_mysql_connection', 'query_mysql', 'manual__2025-05-06T06:09:56.652376+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/test_conn.py', '--cfg-path', '/tmp/tmpk5mzx4j9']
[2025-05-06T06:09:58.107+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask query_mysql
[2025-05-06T06:09:58.174+0000] {task_command.py:426} INFO - Running <TaskInstance: test_mysql_connection.query_mysql manual__2025-05-06T06:09:56.652376+00:00 [running]> on host 9d5cd6f20b63
[2025-05-06T06:09:58.285+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_mysql_connection' AIRFLOW_CTX_TASK_ID='query_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T06:09:56.652376+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T06:09:56.652376+00:00'
[2025-05-06T06:09:58.286+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-06T06:09:58.312+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-05-06T06:10:36.311+0000] {logging_mixin.py:188} INFO - Error executing query: (2005, "Unknown server host 'mysql' (-3)")
[2025-05-06T06:10:36.313+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-06T06:10:36.315+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-06T06:10:36.334+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_mysql_connection, task_id=query_mysql, run_id=manual__2025-05-06T06:09:56.652376+00:00, execution_date=20250506T060956, start_date=20250506T060958, end_date=20250506T061036
[2025-05-06T06:10:36.377+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-06T06:10:36.394+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T06:10:36.398+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
