[2025-05-08T09:57:08.261+0000] {processor.py:161} INFO - Started process (PID=5094) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:57:08.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T09:57:08.263+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:57:08.262+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:57:08.380+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:57:08.367+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T09:57:08.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:57:08.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.149 seconds
[2025-05-08T09:57:38.782+0000] {processor.py:161} INFO - Started process (PID=5130) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:57:38.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T09:57:38.784+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:57:38.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:57:38.852+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:57:38.847+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T09:57:38.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:57:38.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.099 seconds
[2025-05-08T09:58:09.397+0000] {processor.py:161} INFO - Started process (PID=5166) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:58:09.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T09:58:09.399+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:58:09.399+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:58:09.446+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:58:09.443+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T09:58:09.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:58:09.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.076 seconds
[2025-05-08T09:58:39.784+0000] {processor.py:161} INFO - Started process (PID=5202) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:58:39.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T09:58:39.786+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:58:39.786+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:58:39.847+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:58:39.840+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T09:58:39.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:58:39.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.095 seconds
[2025-05-08T09:59:10.310+0000] {processor.py:161} INFO - Started process (PID=5238) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:59:10.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T09:59:10.312+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:59:10.311+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:59:10.372+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:59:10.368+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T09:59:10.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:59:10.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.094 seconds
[2025-05-08T09:59:38.940+0000] {processor.py:161} INFO - Started process (PID=5274) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:59:38.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T09:59:38.942+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:59:38.941+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:59:39.002+0000] {logging_mixin.py:188} INFO - [2025-05-08T09:59:38.999+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T09:59:39.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T09:59:39.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.090 seconds
[2025-05-08T10:00:09.232+0000] {processor.py:161} INFO - Started process (PID=5310) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:00:09.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:00:09.234+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:00:09.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:00:09.295+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:00:09.290+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:00:09.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:00:09.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.094 seconds
[2025-05-08T10:00:39.694+0000] {processor.py:161} INFO - Started process (PID=5346) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:00:39.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:00:39.696+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:00:39.696+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:00:39.756+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:00:39.752+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:00:39.758+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:00:39.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.091 seconds
[2025-05-08T10:01:10.154+0000] {processor.py:161} INFO - Started process (PID=5382) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:01:10.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:01:10.156+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:01:10.156+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:01:10.203+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:01:10.200+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:01:10.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:01:10.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.073 seconds
[2025-05-08T10:01:40.508+0000] {processor.py:161} INFO - Started process (PID=5418) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:01:40.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:01:40.510+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:01:40.510+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:01:40.562+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:01:40.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 12, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:01:40.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:01:40.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.081 seconds
[2025-05-08T10:02:05.207+0000] {processor.py:161} INFO - Started process (PID=5454) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:02:05.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:02:05.209+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:02:05.209+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:02:05.274+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:02:05.270+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:02:05.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:02:05.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.101 seconds
[2025-05-08T10:02:35.892+0000] {processor.py:161} INFO - Started process (PID=5490) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:02:35.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:02:35.895+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:02:35.894+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:02:35.950+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:02:35.946+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:02:35.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:02:35.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.092 seconds
[2025-05-08T10:03:06.438+0000] {processor.py:161} INFO - Started process (PID=5526) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:03:06.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:03:06.442+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:03:06.441+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:03:06.500+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:03:06.496+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:03:06.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:03:06.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.092 seconds
[2025-05-08T10:03:36.927+0000] {processor.py:161} INFO - Started process (PID=5562) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:03:36.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:03:36.930+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:03:36.930+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:03:36.993+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:03:36.989+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:03:36.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:03:37.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.102 seconds
[2025-05-08T10:04:07.373+0000] {processor.py:161} INFO - Started process (PID=5598) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:04:07.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:04:07.376+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:04:07.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:04:07.434+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:04:07.430+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:04:07.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:04:07.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.096 seconds
[2025-05-08T10:04:37.758+0000] {processor.py:161} INFO - Started process (PID=5634) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:04:37.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:04:37.760+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:04:37.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:04:37.811+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:04:37.807+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:04:37.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:04:37.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.082 seconds
[2025-05-08T10:05:08.143+0000] {processor.py:161} INFO - Started process (PID=5670) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:05:08.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:05:08.145+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:05:08.145+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:05:08.195+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:05:08.192+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:05:08.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:05:08.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.078 seconds
[2025-05-08T10:05:38.669+0000] {processor.py:161} INFO - Started process (PID=5706) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:05:38.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:05:38.671+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:05:38.671+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:05:38.718+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:05:38.715+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:05:38.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:05:38.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.072 seconds
[2025-05-08T10:06:09.092+0000] {processor.py:161} INFO - Started process (PID=5742) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:06:09.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:06:09.094+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:06:09.094+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:06:09.139+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:06:09.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:06:09.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:06:09.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.074 seconds
[2025-05-08T10:06:39.510+0000] {processor.py:161} INFO - Started process (PID=5778) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:06:39.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:06:39.512+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:06:39.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:06:39.558+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:06:39.555+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:06:39.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:06:39.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.073 seconds
[2025-05-08T10:07:10.041+0000] {processor.py:161} INFO - Started process (PID=5814) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:07:10.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:07:10.043+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:07:10.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:07:10.089+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:07:10.086+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:07:10.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:07:10.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.070 seconds
[2025-05-08T10:07:40.554+0000] {processor.py:161} INFO - Started process (PID=5850) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:07:40.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:07:40.556+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:07:40.556+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:07:40.606+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:07:40.602+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:07:40.607+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:07:40.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.078 seconds
[2025-05-08T10:08:11.061+0000] {processor.py:161} INFO - Started process (PID=5886) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:08:11.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:08:11.063+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:08:11.063+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:08:11.116+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:08:11.113+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:08:11.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:08:11.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.080 seconds
[2025-05-08T10:08:41.515+0000] {processor.py:161} INFO - Started process (PID=5922) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:08:41.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:08:41.517+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:08:41.516+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:08:41.573+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:08:41.569+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:08:41.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:08:41.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.094 seconds
[2025-05-08T10:09:12.207+0000] {processor.py:161} INFO - Started process (PID=5958) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:09:12.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:09:12.209+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:09:12.209+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:09:12.255+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:09:12.252+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:09:12.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:09:12.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.071 seconds
[2025-05-08T10:09:42.645+0000] {processor.py:161} INFO - Started process (PID=5994) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:09:42.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:09:42.647+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:09:42.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:09:42.699+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:09:42.695+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:09:42.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:09:42.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.082 seconds
[2025-05-08T10:10:13.088+0000] {processor.py:161} INFO - Started process (PID=6030) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:10:13.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:10:13.090+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:10:13.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:10:13.140+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:10:13.137+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:10:13.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:10:13.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.082 seconds
[2025-05-08T10:10:43.593+0000] {processor.py:161} INFO - Started process (PID=6066) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:10:43.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:10:43.594+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:10:43.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:10:43.642+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:10:43.639+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:10:43.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:10:43.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.075 seconds
[2025-05-08T10:11:14.027+0000] {processor.py:161} INFO - Started process (PID=6102) to work on /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:11:14.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_dw_dag.py for tasks to queue
[2025-05-08T10:11:14.029+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:11:14.029+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:11:14.085+0000] {logging_mixin.py:188} INFO - [2025-05-08T10:11:14.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_dw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_dw_dag.py", line 16, in <module>
    from transform_dim_payments import transform_dim_payments
ImportError: cannot import name 'transform_dim_payments' from 'transform_dim_payments' (/opt/airflow/dags/transform_dim_payments.py)
[2025-05-08T10:11:14.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_dw_dag.py
[2025-05-08T10:11:14.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_dw_dag.py took 0.081 seconds
